service: animal-bot

plugins:
- serverless-webpack
- "@kalarrs/serverless-project-utils"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  timeout: 5
  memorySize: 128

  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY, file(../serverless.yml):provider.environment.TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET, file(../serverless.yml):provider.environment.TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN_KEY: ${env:TWITTER_ACCESS_TOKEN_KEY, file(../serverless.yml):provider.environment.TWITTER_ACCESS_TOKEN_KEY}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET, file(../serverless.yml):provider.environment.TWITTER_ACCESS_TOKEN_SECRET}

functions:
  detectRareAlien:
    handler: src/handler.detectRareAlien
    events:
    - http:
        path: detect-rare-alien
        method: get

  getImagesCsvMappings:
    handler: src/handler.getImagesCsvMappings
    events:
    - http:
        path: images/csv-mappings
        method: get

  updateImagesCsvMapping:
    handler: src/handler.updateImagesCsvMapping
    events:
    - http:
        cors: true
        path: images/csv-mappings/{csvMappingId}
        method: put

custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
